name: Generate Favicons

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    paths:
      - '*.svg'
      - '.github/workflows/gen-favicons.yml'
  workflow_dispatch:         # Allow manual runs

jobs:
  build-favicons:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get install -y librsvg2-bin imagemagick

      - name: Generate 64x64 PNGs
        run: |
          mkdir -p output
          sed 's/#231f20/#e53a5a/Ig' Pions_Logo_Main.svg > Pions_Logo_Pink.svg
          rsvg-convert -w 64 -h 64 -f png Pions_Logo_Pink.svg -o "output/favicon_64x64.png"

      - name: Upload PNGs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: favicons
          path: output/

