name: Generate Logos

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:
  push:
    paths:
      - 'Pions_Logo_Main.svg'
      - '.github/workflows/generate-pngs.yml'

jobs:
  build-logos:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y librsvg2-bin imagemagick

      - name: Create color variants
        run: |
          mkdir -p variants
          cp Pions_Logo_Main.svg variants/Pions_Logo_Main.svg

          sed 's/#231f20/#e53a5a/Ig' Pions_Logo_Main.svg > variants/Pions_Logo_Pink.svg
          sed 's/none/#531219/Ig' variants/Pions_Logo_Pink.svg > variants/Pions_Logo_Pink_BurgunderBackground.svg
          sed 's/#231f20/#ffffff/Ig' Pions_Logo_Main.svg > variants/Pions_Logo_White.svg
          sed 's/#231f20/#531219/Ig' Pions_Logo_Main.svg > variants/Pions_Logo_Burgunder.svg

      - name: Convert SVGs to square padded PNGs (512x512)
        run: |
          mkdir -p output

          for svg in variants/*.svg; do
            base=$(basename "$svg" .svg)

            rsvg-convert -w 512 -f png "$svg" | \
              convert - -gravity center -background none -extent 512x512 "output/${base}.png"
          done

      - name: Generate 64x64 full logo PNG
        run: |
          mkdir -p favicons
          rsvg-convert -w 64 -h 64 -f png variants/Pions_Logo_Pink.svg -o "favicons/favicon_logo_64x64.png"
          convert favicons/favicon_logo_64x64.png favicons/favicon_logo.ico

      - name: Generate dot logo PNGs
        run: |
          sizes=(32 64 180 192)
          for s in "${sizes[@]}"; do
            rsvg-convert -w "$s" -h "$s" -f png favicon.svg -o "favicons/favicon_${s}x${s}.png"
          done
          convert favicons/favicon_64x64.png favicons/favicon.ico

      - name: Prepare release bundle
        run: |
          mkdir -p release
          cp variants/*.svg release/
          cp output/*.png release/
          cp favicons/* release/
          zip -j release/pions-logos.zip release/*

      - name: Upload all release assets
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          files: release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}